### ISSUE TITLE
CitraRNG does not open

### ISSUE THREAD

**Issue by ShinyHunterRob** [Admiral-Fish/CitraRNG#19]
Hey. I'm trying to use CitraRNG, but I keep getting an error. All the files are in the right place so I don't know what could be wrong. And it's bothering me a lot.

Could you look into this, please? Thank you.

```
C:\Users\Rob\AppData\Local\Citra\nightly-mingw\scripting>py citrarng.py
Traceback (most recent call last):
  File "C:\Users\Rob\AppData\Local\Citra\nightly-mingw\scripting\citrarng.py", line 10, in <module>
    mainWindow = MainWindow()
                 ^^^^^^^^^^^^
  File "C:\Users\Rob\AppData\Local\Citra\nightly-mingw\scripting\main_window.py", line 16, in __init__
    super(MainWindow, self).__init__(parent)
TypeError: object.__init__() takes exactly one argument (the instance to initialize)
```

**Comment by sIFeAiN** [comment]
Hello, im having a similar issue, the script (`citrarng.py`) tries to run but closes.
I also installed `Pyside 6` and correctly moved allthe `.py` files into the `scripting` folder, however for some reason i cannot edit `citrarng.py` with `IDLE` since the option doesnt show up but im alredy working on fixing that.

Could there be another problem im not seeing? if so please reach out, this is my first time using citra after a while let alone rng scripts :)

>Edit Fix:
Helo! i managed to fix the problem, first i opened python amd (wich is what you get when you first download python) and i clicked on repair just to be safe. 
After that in my computer i went to settings>system>`choose default apps by file type` and scrolled down to `.py` (or you can just click your start/windows button and search up "default apps" and then scroll all the way down to "choose default apps by file type") then i clicked on the python icon and choosed to asign it by default. 
Then i went back opened citra, loaded my save and went into the scripting folder, right clicked on the `citrarng.py` script and finally the "more options" button showed up at the bottom, clicked on that and then `edit with idle` showed up, from there you just have to click on the 3.10 version and press f5 on your keyboard. 
Voila!! 

im writing this just in case anyone in the future gets this problem
